export { default as Root } from './root.svelte';
export { default as Body } from './body.svelte';
export { default as Content } from './content.svelte';
export { default as Header } from './header.svelte';
export { default as Title } from './title.svelte';
export { default as Subtitle } from './subtitle.svelte';
export { default as Text } from './text.svelte';
export { default as Footer } from './footer.svelte';
export { default as Action } from './action.svelte';
